apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark.fullname" . }}-master
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      {{- include "spark.selectorLabels" . | nindent 6 }}
      component: master
  template:
    metadata:
      labels:
        {{- include "spark.selectorLabels" . | nindent 8 }}
        component: master
    spec:
      containers:
        - name: spark-master
          image: "{{ .Values.master.image }}:{{ .Values.master.tag }}"
          ports:
            {{- range $port := .Values.master.service.ports }}
            - containerPort: {{ $port.port }}
              name: {{ $port.name }}
            {{- end }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}