apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hbase.fullname" . }}
  labels:
    {{- include "hbase.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hbase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hbase.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $port := .Values.service.ports }}
            - containerPort: {{ $port.port }}
              name: {{ $port.name }}
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /hbase-data
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "hbase.fullname" . }}-pvc
      {{- end }}