apiVersion: v1
kind: Service
metadata:
  name: {{ include "hbase.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: master-ui
      port: 16010
      targetPort: 16010
    - name: master
      port: 16000
      targetPort: 16000
    - name: regionserver
      port: 16020
      targetPort: 16020
  selector:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}