apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnn-model.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "gnn-model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}