apiVersion: v2
name: aml-platform
description: AML Platform with GraphAML, GNN, JanusGraph, HBase and Spark
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: graphaml
    version: 0.1.0
    repository: file://./charts/graphaml
  - name: gnn-model
    version: 0.1.0
    repository: file://./charts/gnn-model
  - name: janusgraph
    version: 0.1.0
    repository: file://./charts/janusgraph
  - name: hbase
    version: 0.1.0
    repository: file://./charts/hbase
  - name: spark
    version: 0.1.0
    repository: file://./charts/spark